utils::globalVariables(c("Actual_Time", "Clock_Status", "Corrected_Time", "Dataset", "Expression", "First_True",
                         "FlatContrib", "Freq", "Gene", "Gene_Name", "Group", "Group_1", "Group_2", "Group_3", "Is_True",
                         "LogThresh", "MaxLik_Ratio", "MaxLik_Ratio_capped", "MaxLik_Ratio_trans",
                         "Mean_Theta", "PeakNum_Ratio", "Perc_Flat", "Pval", "Replicate", "Rsquared", "Theta", "Time",
                         "Time_mod24", "flagged_1st", "flagged_2nd", "i", "ind_num", "j",
                         "max_1st_peak", "max_2nd_peak", "rank_pval", "rank_rsquared", "rank_sum",
                         "test_timeseries_matched_name", "time_1st_peak", "time_2nd_peak",
                         "timeseries_ind", "timeseries_name", "weighted_mean_time_pred", "name", "value",
                         "Pval.adj", "MESOR", "Phase", "rAMP", "Sig",
                         "MRL", "Rayleigh_p", "Amp_CV", "n_groups", "occurrence",
                         "rank_mrl", "rank_amp_cv", "n_tp",
                         "Projection", "Predicted_Time", "PC", "PredError", "Condition",
                         "Error", "Facet"))
